version: '2'

services:
  riff:
    build: .
    cap_add:
      - SYS_PTRACE
    ulimits:
      nofile: 65536
    ports:
      - '8080:8080'
      - '9000:9000'
    networks:
      - app-network

networks:
  app-network:
    name: app-network