addSbtPlugin("ch.epfl.lamp"           % "sbt-dotty"                 % "0.4.2")
addSbtPlugin("com.typesafe.sbt"       % "sbt-git"                   % "0.9.3")
addSbtPlugin("com.timushev.sbt"       % "sbt-updates"               % "0.5.1")
addSbtPlugin("org.scala-js"           % "sbt-scalajs"               % "1.3.1")
addSbtPlugin("org.portable-scala"     % "sbt-scalajs-crossproject"  % "1.0.0")